server:
  port: 18083
spring:
  application:
    name: canal
  redis:
    host: 192.168.211.132
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
ribbon:
  eager-load:
    enabled: true #饥饿加载 默认的是懒加载
  ReadTimeout: 100000 #设置超时时间
#canal配置
canal:
  client:
    instances:
      example:
        host: 192.168.211.132
        port: 11111