server:
  port: 18090
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.211.132:3306/changgou_order?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 192.168.211.132
    port: 6379
  main:
    allow-bean-definition-overriding: true #允许bean名字可以重复
  #配置RabbitMQ
  rabbitmq:
    host: 192.168.211.132
    port: 5672
  alibaba:
    seata:
      tx-service-group: my_test_tx_group

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 5000
  eager-load:
    enabled: true # 开启饥饿加载 系统启动 则初始化。

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 10s
          strategy: SEMAPHORE  #信号量模式 线程共享
mq:
  pay:
    exchange:
      order: exchange.order
    queue:
      order: queue.order
    routing:
      key: queue.order